name: docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: docker-back
        run: |
          cd words
          docker build -t chachou/docker-back .

      - name: docker-web
        run: |
          cd web
          docker build -t chachou/docker-web
          
      - name: docker-db
        run: |
          cd db
          docker build -t chachou/docker-db
